site_name: ML и анализ данных по-человечески
site_description: Материалы канала в формате сайта
theme:
  name: material
  language: ru
plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/telegram
      title: ML и анализ данных по-человечески
      link: https://t.me/ML_DS_one

extra_css:
  - stylesheets/quick-nav.css

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true
